# Generated by Django 5.2.6 on 2025-10-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0004_doctor_appointmenthistory_doctor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
    ]
