# Generated by Django 5.2.6 on 2025-10-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_appointmenthistory_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, choices=[('General Checkup', 'General Checkup'), ('Periodontist', 'Periodontist'), ('Orthodontics', 'Orthodontics'), ('Endodontist', 'Endodontist'), ('Oral Surgery', 'Oral Surgery'), ('Prosthodontist', 'Prosthodontist')], max_length=255, null=True),
        ),
    ]
