# Generated by ChatGPT - add status field to AppointmentHistory
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistory',
            name='status',
            field=models.CharField(choices=[('unvisited', 'Unvisited'), ('visited', 'Visited')], default='unvisited', max_length=20),
        ),
    ]
