# Generated by Django 5.2.6 on 2025-11-17 07:59

import django.db.models.deletion
from django.db import migrations, models


def create_default_services(apps, schema_editor):
    """Create default dental services."""
    Service = apps.get_model('dental', 'Service')
    
    services = [
        'General Checkup',
        'Periodontist',
        'Orthodontics',
        'Endodontist',
        'Oral Surgery',
        'Prosthodontist',
    ]
    
    for service_name in services:
        Service.objects.get_or_create(name=service_name)


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0007_add_status_to_appointmenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_services, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='appointmenthistory',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointmenthistory',
            name='status',
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='visited',
            field=models.CharField(choices=[('unvisited', 'Unvisited'), ('visited', 'Visited')], default='unvisited', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='dental.service'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='dental.service'),
        ),
    ]
