# Generated by Django 5.2.6 on 2025-11-17 07:59

from django.db import migrations


def create_default_services(apps, schema_editor):
    """Create default dental services."""
    Service = apps.get_model('dental', 'Service')
    
    services = [
        'General Checkup',
        'Periodontist',
        'Orthodontics',
        'Endodontist',
        'Oral Surgery',
        'Prosthodontist',
    ]
    
    for service_name in services:
        Service.objects.get_or_create(name=service_name)


def reverse_create_services(apps, schema_editor):
    """Remove default services."""
    Service = apps.get_model('dental', 'Service')
    Service.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0008_service_remove_appointmenthistory_service_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_services, reverse_create_services),
    ]
